name: Build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "master"]

jobs:
  global:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Add Musleabi Target
      run: rustup target add armv5te-unknown-linux-musleabi
    - name: Build
      run: cargo build --verbose
  # add back when libs are merged in
  # libs:
  #
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Add Musleabi Target
  #     run: rustup target add armv5te-unknown-linux-musleabi
  #   - name: Build
  #     run: cargo build --verbose --package lib
  #
